//
// Type
//

/** @see https://developer.paypal.com/docs/api/orders/v2/#definition-eci_flag */
export type PayPalECIFlag = "MASTERCARD_NON_3D_SECURE_TRANSACTION" | "MASTERCARD_ATTEMPTED_AUTHENTICATION_TRANSACTION" | "MASTERCARD_FULLY_AUTHENTICATED_TRANSACTION" | "FULLY_AUTHENTICATED_TRANSACTION" | "ATTEMPTED_AUTHENTICATION_TRANSACTION" | "NON_3D_SECURE_TRANSACTION";